API:
  KEY:
  URL: "https://maps.googleapis.com/maps/api/distancematrix/json?"

max_driving_time: 1200 # in seconds

input:
  supermarkets_file: data/suppliers_penang.csv
  grid_geocode_file: data/grid_center_geocode.csv
  grid_population_file: data/penang_grid_population.csv
  grid_shape_file: data/penang_grid_EPSG3857_WGS84_v3.shp

output:
  grid_to_supermarket_dist_raw: data/grid_to_supermarket_dist.json
  grid_to_supermarket_dist_data: data/grid_to_supermarket_dist.csv
  supermarket_density_file: data/supermarket_density.csv
  supermarket_density_shape_file: data/supermarket_density.shp

logging:
  version: 1
  root:
    level: INFO
    handlers: [console, logfile]
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s--: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
    logfile:
      class: logging.FileHandler
      level: INFO
      filename: log/dist_matrix_api.log
      formatter: simple
      mode: "w"
