API:
  KEY:
  URL: "https://maps.googleapis.com/maps/api/place/textsearch/json?"

input:
  filename: data/grid_center_geocode.csv
  query: supermarket,grocery
  radius: 2000

output:
  existing_supermarkets_raw: data/suppliers_penang_raw.json
  existing_supermarkets_data: data/suppliers_penang.csv

logging:
  version: 1
  root:
    level: INFO
    handlers: [console, logfile]
  formatters:
    simple:
      format: '%(asctime)s %(levelname)s--: %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
    logfile:
      class: logging.FileHandler
      level: INFO
      filename: log/places_finder.log
      formatter: simple
      mode: "w"
